name: Node.js CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        if [ ! -f package-lock.json ]; then
          npm install
        fi
        npm ci
    - name: Build Docker image
      run: docker build -t my-node-app .
